- name: Node exporter installation
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: install node-exporter
    ansible.builtin.dnf:
      name: golang-github-prometheus-node-exporter
      state: latest
  - name: move service file
    ansible.builtin.copy:
      src: node_exporter.service
      dest: /etc/systemd/system/node_exporter.service
      owner: root
      group: root
  - name: start node-exporter
    ansible.builtin.service:
      name: node_exporter
      state: started
      daemon_reload: true
