- hosts: client
  tasks:
    - name: Activate virtual environment and run pipeline_script.py in directories
      ansible.builtin.shell: |
        cd /home/ec2-user/data/pdb70/{{ item.dir }}
        source /home/ec2-user/data/myvenv/bin/activate
        nohup python3 pipeline_script.py experiment_ids_{{ item.id }}.fasta experiment_ids_{{ item.id }}.csv &
      loop:
        - { id: '1', dir: '1' }
        - { id: '2', dir: '2' }

- hosts: cluster
  tasks:
    - name: Activate virtual environment and run specific pipeline_script.py for each cluster node
      ansible.builtin.shell: |
        source /home/ec2-user/data/myvenv/bin/activate
        cd /home/ec2-user/data/pdb70
        nohup python3 pipeline_script.py experiment_ids_{{ item.id }}.fasta experiment_ids_{{ item.id }}.csv &
      loop:
        - { host: 'cluster1', id: '3' }
        - { host: 'cluster2', id: '4' }
        - { host: 'cluster3', id: '5' }
        - { host: 'cluster4', id: '6' }
      when: inventory_hostname == item.host